spring:
  datasource:
    #??
#    url: jdbc:mariadb://43.202.55.53:3306/drug
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: ssafyE204
#    password: 1793
    url: jdbc:mysql://localhost:3307/dong_ddo_nong
    driver-class-name: org.mariadb.jdbc.Driver
    username: ssafy
    password: ssafy
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
